import AsyncStorage from "@react-native-async-storage/async-storage";
import React, {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useRef,
  useState,
} from "react";
import {
  BleManager,
  type Device as BleDevice,
  type Subscription,
} from "react-native-ble-plx";

import {
  COMMAND_CHARACTERISTIC_UUID,
  DEVICE_INFO_CHARACTERISTIC_UUID,
  TELEMETRY_CHARACTERISTIC_UUID,
  WEARBRIDGE_SERVICE_UUID,
  encodeCommand,
  parseDeviceInfo,
  parseTelemetry,
  type BridgeTelemetry,
} from "@/bridge/protocol";

export interface WatchDevice {
  /** The CoreBluetooth identifier used to reconnect to this peripheral. */
  id: string;
  /** Stable ID generated by the Wear OS companion. */
  watchId: string;
  name: string;
  model: string;
  macAddress: string;
  isConnected: boolean;
  lastSync: string;
  firmwareVersion: string;
  /** Null means the watch has not supplied this metric. */
  heartRate: number | null;
  steps: number | null;
  calories: number | null;
  distance: number | null;
  activeMinutes: number | null;
  batteryLevel: number | null;
  isCharging: boolean;
  rssi: number;
}

export type BluetoothState =
  | "unknown"
  | "disabled"
  | "enabled"
  | "unauthorized";
export interface DiscoveredDevice {
  id: string;
  name: string;
  model: string;
  macAddress: string;
  rssi: number;
}

interface WatchContextType {
  devices: WatchDevice[];
  discoveredDevices: DiscoveredDevice[];
  connectedDevice: WatchDevice | null;
  bluetoothState: BluetoothState;
  isScanning: boolean;
  isSyncing: boolean;
  enableBluetooth: () => void;
  disableBluetooth: () => void;
  startScan: () => Promise<void>;
  stopScan: () => void;
  pairDevice: (discovered: DiscoveredDevice) => Promise<void>;
  connectDevice: (id: string) => Promise<void>;
  disconnectDevice: (id: string) => void;
  removeDevice: (id: string) => void;
  syncDevice: (id: string) => Promise<void>;
}

const STORAGE_KEY = "@wearbridge_devices_v3";

const WatchContext = createContext<WatchContextType | null>(null);

function mapBleState(state: string): BluetoothState {
  switch (state) {
    case "PoweredOn":
      return "enabled";
    case "PoweredOff":
      return "disabled";
    case "Unauthorized":
      return "unauthorized";
    default:
      return "unknown";
  }
}

function decodeBase64Utf8(value: string): string {
  const binary = globalThis.atob(value);
  const bytes = Uint8Array.from(binary, (character) => character.charCodeAt(0));
  return new TextDecoder().decode(bytes);
}

function encodeBase64Utf8(value: string): string {
  const bytes = new TextEncoder().encode(value);
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return globalThis.btoa(binary);
}

function initialDevice(discovered: DiscoveredDevice): WatchDevice {
  return {
    id: discovered.id,
    watchId: discovered.id,
    name: discovered.name,
    model: discovered.model,
    macAddress: discovered.id,
    isConnected: false,
    batteryLevel: null,
    lastSync: "Not yet",
    firmwareVersion: "Unknown",
    heartRate: null,
    steps: null,
    calories: null,
    distance: null,
    activeMinutes: null,
    isCharging: false,
    rssi: discovered.rssi,
  };
}

function withTelemetry(
  device: WatchDevice,
  telemetry: BridgeTelemetry,
): WatchDevice {
  return {
    ...device,
    heartRate: telemetry.heartRate ?? device.heartRate,
    steps: telemetry.steps ?? device.steps,
    calories: telemetry.calories ?? device.calories,
    distance:
      telemetry.distanceMeters === undefined
        ? device.distance
        : Math.round((telemetry.distanceMeters / 1000) * 100) / 100,
    activeMinutes: telemetry.activeMinutes ?? device.activeMinutes,
    batteryLevel: telemetry.batteryLevel ?? device.batteryLevel,
    isCharging: telemetry.isCharging ?? device.isCharging,
    lastSync: telemetry.capturedAt
      ? new Date(telemetry.capturedAt).toLocaleTimeString()
      : new Date().toLocaleTimeString(),
  };
}

export function WatchProvider({ children }: { children: React.ReactNode }) {
  const [devices, setDevices] = useState<WatchDevice[]>([]);
  const [discoveredDevices, setDiscoveredDevices] = useState<
    DiscoveredDevice[]
  >([]);
  const [bluetoothState, setBluetoothState] =
    useState<BluetoothState>("unknown");
  const [isScanning, setIsScanning] = useState(false);
  const [isSyncing, setIsSyncing] = useState(false);

  const bleManagerRef = useRef<BleManager | null>(null);
  const devicesRef = useRef<WatchDevice[]>([]);
  const scanTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const scanResolveRef = useRef<(() => void) | null>(null);
  const telemetrySubscriptionsRef = useRef(new Map<string, Subscription>());
  const disconnectSubscriptionsRef = useRef(new Map<string, Subscription>());

  useEffect(() => {
    devicesRef.current = devices;
  }, [devices]);

  const persistDevices = useCallback((next: WatchDevice[]) => {
    devicesRef.current = next;
    setDevices(next);
    AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(next)).catch(() => {});
  }, []);

  const updateDevices = useCallback(
    (update: (current: WatchDevice[]) => WatchDevice[]) => {
      persistDevices(update(devicesRef.current));
    },
    [persistDevices],
  );

  const applyTelemetry = useCallback(
    (id: string, telemetry: BridgeTelemetry) => {
      updateDevices((current) =>
        current.map((device) =>
          device.id === id ? withTelemetry(device, telemetry) : device,
        ),
      );
    },
    [updateDevices],
  );

  const stopScan = useCallback(() => {
    bleManagerRef.current?.stopDeviceScan();
    if (scanTimeoutRef.current) clearTimeout(scanTimeoutRef.current);
    scanTimeoutRef.current = null;
    scanResolveRef.current?.();
    scanResolveRef.current = null;
    setIsScanning(false);
  }, []);

  useEffect(() => {
    AsyncStorage.getItem(STORAGE_KEY)
      .then((savedDevices) => {
        if (savedDevices) {
          const parsed = JSON.parse(savedDevices) as WatchDevice[];
          persistDevices(
            parsed.map((device) => ({
              ...device,
              watchId: device.watchId || device.id,
              isConnected: false,
              heartRate: device.heartRate || null,
              steps: device.steps ?? null,
              calories: device.calories ?? null,
              distance: device.distance ?? null,
              activeMinutes: device.activeMinutes ?? null,
              batteryLevel: device.batteryLevel ?? null,
            })),
          );
        }
      })
      .catch(() => {});
  }, [persistDevices]);

  useEffect(() => {
    const manager = new BleManager();
    bleManagerRef.current = manager;
    const stateSubscription = manager.onStateChange(
      (state) => setBluetoothState(mapBleState(state)),
      true,
    );

    return () => {
      stopScan();
      stateSubscription.remove();
      telemetrySubscriptionsRef.current.forEach((subscription) =>
        subscription.remove(),
      );
      disconnectSubscriptionsRef.current.forEach((subscription) =>
        subscription.remove(),
      );
      telemetrySubscriptionsRef.current.clear();
      disconnectSubscriptionsRef.current.clear();
      manager.destroy();
      bleManagerRef.current = null;
    };
  }, [stopScan]);

  const monitorDevice = useCallback(
    async (device: BleDevice, discovered?: DiscoveredDevice) => {
      const manager = bleManagerRef.current;
      if (!manager) throw new Error("Bluetooth is not ready");

      const connected = await manager.isDeviceConnected(device.id);
      const peripheral = connected
        ? device
        : await manager.connectToDevice(device.id, { timeout: 15000 });
      await peripheral.discoverAllServicesAndCharacteristics();

      const infoCharacteristic = await manager.readCharacteristicForDevice(
        peripheral.id,
        WEARBRIDGE_SERVICE_UUID,
        DEVICE_INFO_CHARACTERISTIC_UUID,
      );
      if (!infoCharacteristic.value) {
        throw new Error("This device is not running the WearBridge companion");
      }
      const info = parseDeviceInfo(decodeBase64Utf8(infoCharacteristic.value));

      let next =
        devicesRef.current.find(
          (candidate) =>
            candidate.id === peripheral.id ||
            candidate.watchId === info.watchId,
        ) ??
        initialDevice(
          discovered ?? {
            id: peripheral.id,
            name: peripheral.name ?? "WearBridge Watch",
            model: "Wear OS Watch",
            macAddress: peripheral.id,
            rssi: peripheral.rssi ?? -70,
          },
        );
      next = {
        ...next,
        id: peripheral.id,
        watchId: info.watchId,
        name: info.displayName,
        model: info.model,
        firmwareVersion: info.firmwareVersion,
        macAddress: peripheral.id,
        isConnected: true,
        rssi: peripheral.rssi ?? next.rssi,
      };

      try {
        const telemetryCharacteristic =
          await manager.readCharacteristicForDevice(
            peripheral.id,
            WEARBRIDGE_SERVICE_UUID,
            TELEMETRY_CHARACTERISTIC_UUID,
          );
        if (telemetryCharacteristic.value) {
          next = withTelemetry(
            next,
            parseTelemetry(decodeBase64Utf8(telemetryCharacteristic.value)),
          );
        }
      } catch {
        // The notification subscription below remains the source of truth.
      }

      updateDevices((current) => {
        const disconnected = current.map((candidate) => ({
          ...candidate,
          isConnected: false,
        }));
        const index = disconnected.findIndex(
          (candidate) =>
            candidate.id === peripheral.id ||
            candidate.watchId === info.watchId,
        );
        if (index === -1) return [...disconnected, next];
        disconnected[index] = next;
        return disconnected;
      });

      telemetrySubscriptionsRef.current.get(peripheral.id)?.remove();
      telemetrySubscriptionsRef.current.set(
        peripheral.id,
        manager.monitorCharacteristicForDevice(
          peripheral.id,
          WEARBRIDGE_SERVICE_UUID,
          TELEMETRY_CHARACTERISTIC_UUID,
          (error, characteristic) => {
            if (error) {
              if (error.errorCode !== 2) {
                console.warn("WearBridge telemetry subscription failed", error);
              }
              return;
            }
            if (!characteristic?.value) return;
            try {
              applyTelemetry(
                peripheral.id,
                parseTelemetry(decodeBase64Utf8(characteristic.value)),
              );
            } catch (parseError) {
              console.warn("WearBridge sent invalid telemetry", parseError);
            }
          },
        ),
      );

      disconnectSubscriptionsRef.current.get(peripheral.id)?.remove();
      disconnectSubscriptionsRef.current.set(
        peripheral.id,
        manager.onDeviceDisconnected(peripheral.id, () => {
          telemetrySubscriptionsRef.current.get(peripheral.id)?.remove();
          telemetrySubscriptionsRef.current.delete(peripheral.id);
          updateDevices((current) =>
            current.map((candidate) =>
              candidate.id === peripheral.id
                ? { ...candidate, isConnected: false }
                : candidate,
            ),
          );
        }),
      );
    },
    [applyTelemetry, updateDevices],
  );

  const startScan = useCallback(async () => {
    if (bluetoothState !== "enabled") {
      throw new Error("Turn on Bluetooth in iOS Settings before scanning");
    }
    const manager = bleManagerRef.current;
    if (!manager) throw new Error("Bluetooth is not ready");

    stopScan();
    setDiscoveredDevices([]);
    setIsScanning(true);
    const seen = new Set<string>();
    const paired = new Set(devicesRef.current.map((device) => device.id));

    await new Promise<void>((resolve, reject) => {
      scanResolveRef.current = resolve;
      manager.startDeviceScan(
        [WEARBRIDGE_SERVICE_UUID],
        { allowDuplicates: false },
        (error, device) => {
          if (error) {
            manager.stopDeviceScan();
            if (scanTimeoutRef.current) clearTimeout(scanTimeoutRef.current);
            scanTimeoutRef.current = null;
            scanResolveRef.current = null;
            setIsScanning(false);
            reject(new Error(error.message || "Bluetooth scan failed"));
            return;
          }
          if (!device || seen.has(device.id) || paired.has(device.id)) return;
          seen.add(device.id);
          const name =
            device.localName ??
            device.name ??
            `WearBridge ${device.id.slice(-4)}`;
          setDiscoveredDevices((current) => [
            ...current,
            {
              id: device.id,
              name,
              model: "Wear OS Watch",
              macAddress: device.id,
              rssi: device.rssi ?? -70,
            },
          ]);
        },
      );

      scanTimeoutRef.current = setTimeout(() => {
        manager.stopDeviceScan();
        scanTimeoutRef.current = null;
        scanResolveRef.current = null;
        setIsScanning(false);
        resolve();
      }, 10000);
    });
  }, [bluetoothState, stopScan]);

  const pairDevice = useCallback(
    async (discovered: DiscoveredDevice) => {
      stopScan();
      const manager = bleManagerRef.current;
      if (!manager) throw new Error("Bluetooth is not ready");
      const device = await manager.connectToDevice(discovered.id, {
        timeout: 15000,
      });
      try {
        await monitorDevice(device, discovered);
        setDiscoveredDevices((current) =>
          current.filter((candidate) => candidate.id !== discovered.id),
        );
      } catch (error) {
        await manager.cancelDeviceConnection(discovered.id).catch(() => {});
        throw error;
      }
    },
    [monitorDevice, stopScan],
  );

  const connectDevice = useCallback(
    async (id: string) => {
      const manager = bleManagerRef.current;
      if (!manager) throw new Error("Bluetooth is not ready");
      const known = devicesRef.current.find((device) => device.id === id);
      if (!known) throw new Error("Unknown watch");
      const device = await manager.connectToDevice(id, { timeout: 15000 });
      await monitorDevice(device, {
        id,
        name: known.name,
        model: known.model,
        macAddress: known.macAddress,
        rssi: known.rssi,
      });
    },
    [monitorDevice],
  );

  const disconnectDevice = useCallback(
    (id: string) => {
      telemetrySubscriptionsRef.current.get(id)?.remove();
      telemetrySubscriptionsRef.current.delete(id);
      disconnectSubscriptionsRef.current.get(id)?.remove();
      disconnectSubscriptionsRef.current.delete(id);
      bleManagerRef.current?.cancelDeviceConnection(id).catch(() => {});
      updateDevices((current) =>
        current.map((device) =>
          device.id === id ? { ...device, isConnected: false } : device,
        ),
      );
    },
    [updateDevices],
  );

  const removeDevice = useCallback(
    (id: string) => {
      disconnectDevice(id);
      updateDevices((current) => current.filter((device) => device.id !== id));
    },
    [disconnectDevice, updateDevices],
  );

  const syncDevice = useCallback(
    async (id: string) => {
      const manager = bleManagerRef.current;
      const device = devicesRef.current.find(
        (candidate) => candidate.id === id,
      );
      if (!manager || !device?.isConnected) {
        throw new Error("Connect the watch before syncing");
      }

      setIsSyncing(true);
      try {
        await manager.writeCharacteristicWithResponseForDevice(
          id,
          WEARBRIDGE_SERVICE_UUID,
          COMMAND_CHARACTERISTIC_UUID,
          encodeBase64Utf8(encodeCommand("SYNC_NOW", `${Date.now()}`)),
        );
        const characteristic = await manager.readCharacteristicForDevice(
          id,
          WEARBRIDGE_SERVICE_UUID,
          TELEMETRY_CHARACTERISTIC_UUID,
        );
        if (characteristic.value) {
          applyTelemetry(
            id,
            parseTelemetry(decodeBase64Utf8(characteristic.value)),
          );
        }
      } finally {
        setIsSyncing(false);
      }
    },
    [applyTelemetry],
  );

  const enableBluetooth = useCallback(() => {
    bleManagerRef.current
      ?.state()
      .then((state) => setBluetoothState(mapBleState(state)))
      .catch(() => setBluetoothState("unknown"));
  }, []);

  const disableBluetooth = useCallback(() => {
    stopScan();
    for (const device of devicesRef.current.filter(
      (candidate) => candidate.isConnected,
    )) {
      disconnectDevice(device.id);
    }
  }, [disconnectDevice, stopScan]);

  return (
    <WatchContext.Provider
      value={{
        devices,
        discoveredDevices,
        connectedDevice: devices.find((device) => device.isConnected) ?? null,
        bluetoothState,
        isScanning,
        isSyncing,
        enableBluetooth,
        disableBluetooth,
        startScan,
        stopScan,
        pairDevice,
        connectDevice,
        disconnectDevice,
        removeDevice,
        syncDevice,
      }}
    >
      {children}
    </WatchContext.Provider>
  );
}

export function useWatch() {
  const context = useContext(WatchContext);
  if (!context) throw new Error("useWatch must be used within WatchProvider");
  return context;
}
